### ISSUE TITLE
Example of SMTP emails config block for singularity.yaml

### ISSUE THREAD

**Issue by bayendor** [HubSpot/Singularity#1542]
The documentation links for emailtype and email destinations return `404`'s, and the documentation example of:

`emails: Map<EmailType, List<EmailDestination>>` is not particularly helpful.

I'd like to configure all actions to send email to the OWNER.

I'm assuming this is the list of Email Types (I pulled it out of the source code):
```
TASK_LOST
TASK_FAILED
TASK_FAILED_DECOMISSIONED
TASK_FINISHED
TASK_FINISHED_ON_DEMAND
TASK_FINISHED_RUN_ONCE
TASK_FINISHED_SCHEDULED
TASK_FINISHED_LONG_RUNNING
TASK_KILLED
TASK_KILLED_DECOMISSIONED
TASK_KILLED_UNHEALTHY
TASK_SCHEDULED_OVERDUE_TO_FINISH
TASK_RUNNING
```

And this is the Email Destinations:
```
OWNERS
ADMINS
ACTION_TAKER
```

Is it possible to get an example block for what smtp emails would look like to send email to owners for all email types?

Would it look something like this?
```
emails:
  TASK_LOST:
    - OWNER
    - ADMINS
    - ACTION_TAKER
  TASK_FINISHED:
    - OWNER
   TASK_KILLED
    - ACTION_TAKER
```

etc...

**Comment by bayendor** [comment]
Deploying with above config results in:

```
/etc/singularity/singularity.yaml has an error:
  * Incorrect type of value at: smtp.emails; is of type: String, expected: SingularityEmailType
```

**Comment by ssalinas** [comment]
In the example you posted above, seems you might be missing a `:` after `TASK_KILLED`, a working example from our own configs:
```
smtp:
   emails:
    TASK_FAILED:
      - OWNERS
      - ACTION_TAKER
      - ADMINS
```

leaving this issue open so we can fix the docs there

**Comment by bayendor** [comment]
I was able to get the following configuration working:
```
smtp:
  emails:
    TASK_LOST:
      - OWNERS
    TASK_FAILED:
      - OWNERS
    TASK_FAILED_DECOMISSIONED:
      - OWNERS
    TASK_KILLED:
      - OWNERS
    TASK_KILLED_DECOMISSIONED:
      - OWNERS
    TASK_KILLED_UNHEALTHY:
      - OWNERS
    TASK_SCHEDULED_OVERDUE_TO_FINISH:
      - OWNERS
    TASK_FINISHED_ON_DEMAND:
      - OWNERS
    TASK_FINISHED_RUN_ONCE:
      - OWNERS
    TASK_FINISHED_SCHEDULED:
      - OWNERS
    TASK_FINISHED_LONG_RUNNING:
      - OWNERS
```
However it appears that following are not supported email types:

```
    TASK_FINISHED:
      - OWNERS
    TASK_RUNNING:
      - OWNERS
```
