### ISSUE TITLE
docker-compose.yml not working with lasest docker mac

### ISSUE THREAD

**Issue by JC1738** [HubSpot/Singularity#1680]
Updated docker_compose.yml with the following changes to scheduler:

    - SINGULARITY_MAX_HEAP=2048m         //would complain out of memory without this 
    - SINGULARITY_HOSTNAME=localhost    //would complain can't find hostname without this

```
scheduler:
  image: hubspot/singularityservice:0.17.0
  net: host
  environment:
    - DOCKER_HOST
    - LOAD_BALANCER_URI=http://localhost:8080/baragon/v2/request
    - SINGULARITY_MAX_HEAP=2048m
    - SINGULARITY_HOSTNAME=localhost
```

However, still errors out with the following even after those changes:

```
scheduler_1       | Failed to obtain the IP address for 'linuxkit-025000000001'; the DNS service may not be able to resolve it: Name or service not known
```

Running:
Docker CE Version 17.11.0-ce-mac40 (20561)

Thanks,
Jim
